server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:finpal;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org.hibernate.SQL: info
    com.finpal: debug
